export const ErrorCodes = Object.freeze({
    NOT_FOUND: 'NOT_FOUND',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
    FORBIDDEN: 'FORBIDDEN',
    INVALID_TOKEN: 'INVALID_TOKEN',
    REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
    ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
});
